spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webflux
    username: postgres
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

#server:
#  error:
#    include-stacktrace: on_param
